# python-poetry.org/docs/pyproject


[tool.poetry]
name = 'DjAI'
version = '0.0.0.dev0'

description = 'Artificial Intelligence (AI) in Django Applications'

license = 'MIT'

authors = [
  'STEAM for Vietnam Foundation AI & Robotics Educational Initiative <Edu.AI@STEAMforVietNam.org>'
]
maintainers = [
  'STEAM for Vietnam Foundation AI & Robotics Educational Initiative <Edu.AI@STEAMforVietNam.org>'
]

readme = 'README.md'

homepage = 'GitHub.com/Django-AI/DjAI'
repository = 'GitHub.com/Django-AI/DjAI'
documentation = 'GitHub.com/Django-AI/DjAI'

keywords = [
  'Django',
  'Artificial Intelligence',
  'AI'
]
classifiers = [
  'Development Status :: 2 - Pre-Alpha',
  'Environment :: MacOS X',
  'Environment :: Win32 (MS Windows)',
  'Framework :: Django',
  'Framework :: Django :: 3.2',
  'Intended Audience :: Developers',
  'Intended Audience :: Education',
  'Intended Audience :: Financial and Insurance Industry',
  'Intended Audience :: Healthcare Industry',
  'Intended Audience :: Information Technology',
  'Intended Audience :: Legal Industry',
  'Intended Audience :: Manufacturing',
  'Intended Audience :: Science/Research',
  'Intended Audience :: System Administrators',
  'Intended Audience :: Telecommunications Industry',
  'License :: OSI Approved :: MIT License',
  'Operating System :: MacOS',
  'Operating System :: MacOS :: MacOS X',
  'Operating System :: Microsoft',
  'Operating System :: Microsoft :: Windows',
  'Operating System :: Microsoft :: Windows :: Windows 7',
  'Operating System :: Microsoft :: Windows :: Windows 8',
  'Operating System :: Microsoft :: Windows :: Windows 8.1',
  'Operating System :: Microsoft :: Windows :: Windows 10',
  'Operating System :: OS Independent',
  'Operating System :: Other OS',
  'Operating System :: POSIX',
  'Operating System :: POSIX :: Linux',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.9',
  'Programming Language :: Python :: 3.10',
  'Topic :: Education',
  'Topic :: Scientific/Engineering',
  'Topic :: Scientific/Engineering :: Artificial Intelligence',
  'Topic :: Scientific/Engineering :: Human Machine Interfaces',
  'Topic :: Scientific/Engineering :: Image Processing',
  'Topic :: Scientific/Engineering :: Image Recognition',
  'Topic :: Scientific/Engineering :: Information Analysis',
  'Topic :: Scientific/Engineering :: Mathematics',
  'Topic :: Scientific/Engineering :: Visualization',
  'Topic :: Software Development :: Libraries',
  'Topic :: Software Development :: Libraries :: Python Modules'
]

packages = [
  {include = 'djai', from = 'src'}
]

include = [
]
exclude = []


[tool.poetry.dependencies]

# PYTHON
# ======
Python = '^3.8'


# DATA MANAGEMENT & PROCESSING
# ============================
NumPy = '^1.19.5'   # let higher dependencies figure
Pandas = '^1.3.4'
PyArrow = '^6.0.0'
PySpark = '^3.2.0'
Ray = {extras = ['tune'], version = '^1.8.0'}

Pillow = '^8.4.0'   # image processing
# Pillow-SIMD = '^7.0.0'   # complex to install


# MACHINE LEARNING / DEEP LEARNING & RELATED
# ==========================================

# SciKit-Learn & related
Auto-SKLearn = '^0.14.0'
# SciKit-Learn = '^x.y.z'   # let Auto-SKLearn figure

# TensorFlow & related
TensorFlow = '^2.6.1'
TensorFlow-DataSets = '^4.4.0'
TensorFlow-Hub = '^0.12.0'

# Torch & related
Torch = '^1.10.0'
Torch-Model-Archiver = '^0.4.2'
TorchServe = '^0.4.2'

TorchAudio = '^0.10.0'
TorchText = '^0.11.0'
TorchVision = '^0.11.1'

# Hugging Face & related
DataSets = '^1.14.0'
HuggingFace-Hub = '^0.1.0'
Transformers = '^4.12.2'

SentencePiece = '^0.1.96'   # Translation
TIMM = '^0.4.12'   # for Object Detection
# Torch-Scatter = '^2.0.9'   # Table Question Answering - requires Torch first

# Topological Data Analysis (TDA) & related
GUDHI = '^3.4.1'

# Cloud AI/ML Services
Google-Cloud-Translate = '^3.6.0'
GoogleTrans = '^4.0.0rc1'

# Hyper-Parameter Tuning & related
Bayesian-Optimization = '^1.2.0'
ConfigSpace = '^0.4.20'
Hpbandster = '^0.7.4'
Tabulate = '^0.8.9'

# ML Model Explainability & related
LIME = '^0.2.0.1'
SHAP = '^0.40.0'


# NON-ML MODELING
# ===============

# Fuzzy Logic
SciKit-Fuzzy = '^0.4.2'


# MODEL REPOSITORY & RELATED
# ==========================
CloudPickle = '^2.0.0'
JobLib = '^1.1.0'
S3FS = '^2021.10.1'


# DJANGO & RELATED APPLICATION DEVELOPMENT
# ========================================

# Django Core
Django = '^3.2.9'

# Django Polymorphic Models
Django-Polymorphic = '^3.0.0'

# Django Admin Themes
Django-ForestAdmin = '^1.0.5'
Django-Grappelli = '^2.15.3'
Django-Jazzmin = '^2.4.8'

# Django-AutoComplete-Light & related
Django-Autocomplete-Light = '^3.8.2'
Django-Generic-M2M = '^0.3.1'
Django-GM2M = '^1.1.1'
Django-QuerySetSequence = '^0.14'
Django-Tagging = '^0.5.0'
Django-Taggit = '^1.5.1'

# Django GraphQL
# Ariadne = '^0.13.0'   # ariadne 0.13.0 depends on graphql-core>=3.1.0
                        # graphene-django 2.15.0 depends on graphql-core<3
Django-RESTQL = '^0.15.1'
Graphene-Django = '^2.15.0'
Py-GQL = '^0.6.1'
# Strawberry-GraphQL = '^0.84.3'   # conflicts with Graphene-Django

# Django REST Framework
DjangoRESTFramework = '^3.12.4'
DRFPasswordless = '^1.5.7'
CoreAPI = '^2.3.3'   # closely related to Django REST Framework

DjangoRESTFramework-JSONAPI = '^4.2.1'

# Django Filtering
Django-Filter = '^21.1'
DjangoRESTFramework-Filters = '1.0.0.dev2'

# Django Object-Level Permissions
Django-Guardian = '^2.4.0'
Rules = '^3.0'

# Django Model Query Optimization
Django-Model-Query-Graphs = '^0.0.5'

# Django Debugging & Query Profiling
Django-Debug-Toolbar = '^3.2.2'
Django-Query-Profiler = '^0.8'
Django-Silk = '^4.2.0'
Kolo = '^1.2.1'

# Django Extensions & Utilities
Django-Compressor = '2.4.1'
Django-Environ = '^0.8.1'
Django-Extensions = '^3.1.3'
Django-Model-Utils = '^4.2.0'
Django-Storages = '^1.12.3'

# Django CORS Headers
Django-CORS-Headers = '^3.7.0'   # let higher dependencies figure

# Application UIs
Django-HTMX = '^1.6.0'

Django-Plotly-Dash = '^1.6.6'
Dash-Bootstrap-Components = '^0.13.1'
DPD-Static-Support = '^0.0.5'
Django-Bootstrap4 = '^3.0.1'
WhiteNoise = '^5.3.0'

Gradio = '^2.4.1'

Streamlit = '^1.1.0'
Watchdog = '^2.1.6'   # better performance for Streamlit

# Database Connectors/Drivers
MySQLClient = '^2.0.3'
PsycoPG2-binary = '^2.9.1'

# ASGI Web Servers
Channels = '^3.0.4'
Daphne = '^3.0.2'
GUnicorn = '^20.1.0'
Hypercorn = '^0.11.2'
Starlette = '^0.16.0'
Uvicorn = '^0.15.0'


# COMMAND-LINE INTERFACE (CLI)
# ============================
CLICK = '^7.1.2'   # aligned with Streamlit
Colored = '^1.4.3'


# JUPYTER
# =======
Jupyter = '^1.0.0'


# OTHER
# =====
Cython = '^0.29.24'
GitPython = '^3.1.24'
'Ruamel.YAML' = '^0.17.16'
PSUtil = '^5.8.0'
Python-DotEnv = '^0.19.1'
Requests = '^2.25.1'   # let higher dependencies figure
Tqdm = '^4.62.3'


# CLOUD
# =====
# AWSEBCLI = '^3.20.2'


[tool.poetry.dev-dependencies]
Commitizen = '^2.20.0'
PyTest = '^6.2.5'
Pre-Commit = '^2.15.0'


[tool.poetry.scripts]
djai = 'djai.util.cli:djai'


[tool.poetry.extras]
doc = [
  # Sphinx & related
  'Sphinx >= 4.2.0',
  'Sphinx-AutoBuild >= 2021.3.14',
  'SphinxContrib-JSMath >= 1.0.1',

  # Markdown
  'CommonMark >= 0.9.1',
  'MyST-Parser >= 0.15.2',
  'ReCommonMark >= 0.7.1'
]

lint = [
  'Bandit >= 1.7.0',
  'Flake8 >= 4.0.1',
  'MyPy >= 0.910',
  'Prospector >= 1.5.1',
  'PyCodeStyle >= 2.8.0',
  'PyDocStyle >= 6.1.1',
  'PyLama >= 7.7.1',
  'PyLint >= 2.11.1'
]


[tool.poetry.plugins]

[tool.poetry.plugins."blogtool.parsers"]


[tool.poetry.urls]
GitHub = 'GitHub.com/Django-AI/DjAI'


[build-system]
requires = ['Poetry-Core >= 1.0.7']
build-backend = 'poetry.core.masonry.api'
