# python.org/dev/peps/pep-0621


[project]
name = 'Djaizz'
version = '0.0.0.dev16'

description = 'Artificial Intelligence (AI) in Django Applications'
readme = {file = 'README.md', content-type = 'text/markdown', charset = 'UTF-8'}

requires-python = '>= 3.8'

license = {file = 'LICENSE'}

authors = [
  {name = 'STEAM for Vietnam Foundation: AI & Robotics Educational Initiative', email = 'Edu.AI@STEAMforVietNam.org'}
]
maintainers = [
  {name = 'STEAM for Vietnam Foundation: AI & Robotics Educational Initiative', email = 'Edu.AI@STEAMforVietNam.org'}
]

keywords = [
  'Django',

  'Artificial Intelligence',
  'A.I.',
  'AI',

  'application',
  'app',
]

classifiers = [
  'Development Status :: 3 - Alpha',
  # 'Development Status :: 4 - Beta',
  # 'Development Status :: 5 - Production/Stable',
  # 'Development Status :: 6 - Mature',
  'Environment :: MacOS X',
  'Environment :: Win32 (MS Windows)',
  'Framework :: Dash',
  'Framework :: Django',
  'Framework :: Django :: 4.0',
  'Framework :: IPython',
  'Framework :: Jupyter',
  'Framework :: Jupyter :: JupyterLab',
  'Framework :: Jupyter :: JupyterLab :: 4',
  'Framework :: Kedro',
  'Framework :: Matplotlib',
  'Intended Audience :: Developers',
  'Intended Audience :: Education',
  'Intended Audience :: Financial and Insurance Industry',
  'Intended Audience :: Healthcare Industry',
  'Intended Audience :: Information Technology',
  'Intended Audience :: Legal Industry',
  'Intended Audience :: Manufacturing',
  'Intended Audience :: Science/Research',
  'Intended Audience :: System Administrators',
  'Intended Audience :: Telecommunications Industry',
  'Operating System :: MacOS',
  'Operating System :: MacOS :: MacOS X',
  'Operating System :: Microsoft',
  'Operating System :: Microsoft :: Windows',
  'Operating System :: Microsoft :: Windows :: Windows 7',
  'Operating System :: Microsoft :: Windows :: Windows 8',
  'Operating System :: Microsoft :: Windows :: Windows 8.1',
  'Operating System :: Microsoft :: Windows :: Windows 10',
  'Operating System :: OS Independent',
  'Operating System :: Other OS',
  'Operating System :: POSIX',
  'Operating System :: POSIX :: Linux',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.8',
  'Programming Language :: Python :: 3.9',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'Topic :: Education',
  'Topic :: Home Automation',
  'Topic :: Scientific/Engineering',
  'Topic :: Scientific/Engineering :: Artificial Intelligence',
  'Topic :: Scientific/Engineering :: Astronomy',
  'Topic :: Scientific/Engineering :: Atmospheric Science',
  'Topic :: Scientific/Engineering :: Bio-Informatics',
  'Topic :: Scientific/Engineering :: Chemistry',
  'Topic :: Scientific/Engineering :: GIS',
  'Topic :: Scientific/Engineering :: Human Machine Interfaces',
  'Topic :: Scientific/Engineering :: Hydrology',
  'Topic :: Scientific/Engineering :: Image Processing',
  'Topic :: Scientific/Engineering :: Image Recognition',
  'Topic :: Scientific/Engineering :: Information Analysis',
  'Topic :: Scientific/Engineering :: Mathematics',
  'Topic :: Scientific/Engineering :: Medical Science Apps.',
  'Topic :: Scientific/Engineering :: Physics',
  'Topic :: Scientific/Engineering :: Visualization',
  'Topic :: Software Development',
  'Topic :: Software Development :: Libraries',
  'Topic :: Software Development :: Libraries :: Application Frameworks',
  'Topic :: Software Development :: Libraries :: Python Modules',
  'Topic :: Software Development :: User Interfaces',
  'Topic :: Software Development :: Widget Sets',
]


dependencies = [

  # DATA MANAGEMENT & PROCESSING
  # ============================

  'Dask >= 2023.2.1',
  'Distributed >= 2023.2.1',
  'MetaFlow >= 2.8.0',
  # 'NumBa >= 0.56.0',
  'NumPy >= 1.23.5',   # let higher dependencies figure
  'Pandas >= 1.5.3',
  'Pandarallel >= 1.6.4',
  'PyArrow >= 11.0.0',
  'PySpark >= 3.3.2',
  'Ray >= 1.13.0; python_version < "3.11"',
  'SciPy >= 1.10.1',

  'Pillow >= 9.4.0',
  # 'Pillow-SIMD >= 9.0.0',
    # complex to install
  'SciKit-Image >= 0.19.3',

  'Kedro >= 0.18.5; python_version < "3.11"',


  # MACHINE LEARNING / DEEP LEARNING & RELATED
  # ==========================================

  'Imbalanced-Learn >= 0.10.1',
  'StatsModels >= 0.13.5',

  # SciKit-Learn & related
  # 'Auto-SKLearn >= 0.15.0',
    # depends on SciKit-Learn < 0.25.0
  'SciKit-Learn >= 1.2.1',

  # TensorFlow & related
  'TensorFlow >= 2.12.0rc0',
  'TensorFlow-DataSets >= 4.8.3',
  'TensorFlow-Hub >= 0.12.0',

  # Torch & related
  'Torch >= 1.13.1; python_version < "3.11"',
  'Torch-Model-Archiver >= 0.7.1',
  'TorchServe >= 0.7.1',

  'TorchAudio >= 0.13.1; python_version < "3.11"',
  'TorchText >= 0.14.1; python_version < "3.11"',
  'TorchVision >= 0.14.1; python_version < "3.11"',

  # Computer Vision
  'OpenCV-Python >= 4.7.0',

  # Hugging Face & related
  'DataSets >= 2.10.0',
  'HuggingFace-Hub >= 0.12.1',
  'Transformers >= 4.26.1',

  'SentencePiece >= 0.1.97',
  'TIMM >= 0.6.12; python_version < "3.11"',
  # 'Torch-Scatter >= 2.1.0',
    # Table Question Answering - requires Torch first

  # Topological Data Analysis (TDA) & related
  'Giotto-TDA >= 0.6.0; python_version < "3.11"',
  'GUDHI >= 3.7.1',

  # Cloud AI/ML Services
  # 'Google-Cloud-Translate >= 3.10.1',
    # conflicting/long-resolving dependencies
  'GoogleTrans >= 4.0.0rc1',

  # Hyper-Parameter Tuning & related
  'Bayesian-Optimization >= 1.4.2',
  'ConfigSpace >= 0.6.1',
  'Hpbandster >= 0.7.4',
  'Tabulate >= 0.9.0',

  # ML Model Explainability & related
  'CausalNex >= 0.11.0; python_version < "3.11"',
  'LIME >= 0.2.0.1',
  'SHAP >= 0.41.0; python_version < "3.11"',

  # ML Model Management
  # 'MLFLow >= 2.1.1',
    # conflicting/long-resolving dependencies


  # NON-ML MODELING
  # ===============

  # Fuzzy Logic
  'SciKit-Fuzzy >= 0.4.2',


  # FILE SYSTEMS
  # ============
  'FSSpec >= 2023.1.0',
  # 'S3FS >= 2023.1.0',
    # conflicting/long-resolving dependencies


  # MODEL REPOSITORY & RELATED
  # ==========================
  'CloudPickle >= 2.2.1',
  'JobLib >= 1.2.0',


  # DJANGO & RELATED APPLICATION DEVELOPMENT
  # ========================================

  # Django Core
  'Django >= 4.1.7',

  # Django Polymorphic Models
  'Django-Polymorphic >= 3.1.0',

  # Django Admin-related
  'Django-Admin-HStore-Widget >= 1.2.1',
  'Django-Admin-Relation-Links >= 0.2.5',
  'Django-ForestAdmin >= 1.4.4; python_version < "3.11"',
  'Django-Grappelli >= 3.0.4',
  'Django-Jazzmin >= 2.6.0',

  # Django-AutoComplete-Light & related
  'Django-Autocomplete-Light >= 3.9.4',
  'Django-Generic-M2M >= 0.3.1',
  'Django-GM2M >= 1.1.1',
  'Django-QuerySetSequence >= 0.16',
  'Django-Tagging >= 0.5.0',
  'Django-Taggit >= 3.1.0',

  # GraphQL
  'Ariadne >= 0.18.1',
  'Django-GraphQL-Extensions >= 0.1.0',
  'Django-RESTQL >= 0.15.3',
  'GQL >= 3.4.0',
  'Graphene >= 3.2.1',
  'Graphene-Django >= 3.0.0',
  # 'Graphene-Django-Extras >= 0.5.2',
    # conflicting/long-resolving dependencies
  'Graphene-Django-Optimizer >= 0.9.1',
  # 'Graphene-Django-Subscriptions >= 0.0.9',
    # conflicting/long-resolving dependencies
  # 'Graphene-Django-Tools >= 0.21.0',
    # conflicting/long-resolving dependencies
  # 'Graphene-Mongo >= 0.2.14',
    # conflicting/long-resolving dependencies
  # 'Graphene-SQLAlchemy >= 2.3.0',
    # conflicting/long-resolving dependencies
  'GraphQLClient >= 0.2.4',
  'GraphQL-Core >= 3.2.3',
  'GraphQL-Relay >= 3.2.0',
  'Py-GQL >= 0.6.1',
  'SGQLC >= 16.1',
  'Strawberry-GraphQL >= 0.159.0',

  # Django REST Framework & other API-related
  'DjangoRESTFramework >= 3.14.0',
  'DRFPasswordless >= 1.5.8',
  'DRF-Writable-Nested >= 0.6.4',
  'CoreAPI >= 2.3.3',
    # closely related to Django REST Framework
  'CoreAPI-CLI >= 1.0.9',
  'Markdown >= 3.4.1',
    # Markdown support for the browsable API

  'DjangoRESTFramework-JSONAPI >= 6.0.0',
  'DRF-Nested-Routers >= 0.93.4',
  'Django-PolyModels >= 1.7.0',
  'Django-Typed-Models >= 0.12.0',

  'HAL-Codec >= 1.0.2',
  'JSONHyperSchema-Codec >= 1.0.3',
  'OpenAPI-Codec >= 1.3.2',

  'JSONSchema >= 4.17.3',
  'Pydantic >= 1.10.5',

  'HTTPie >= 3.2.1',

  # Django Filtering
  'Django-Filter >= 22.1',
  'DjangoRESTFramework-Filters >= 1.0.0.dev2',

  # Django Object-Level Permissions
  'Django-Guardian >= 2.4.0',
  'Rules >= 3.3',

  # Django Debugging & Query Profiling
  'Django-Debug-Toolbar >= 3.8.1',
  'Django-Query-Profiler >= 0.9',
  'Django-Silk >= 5.0.3',
  'Kolo >= 2.4.2',

  # Django Extensions & Utilities
  'Django-Annoying >= 0.10.6',
  'Django-Choices >= 1.7.2',
  'Django-Compressor >= 4.3.1',
  'Django-Configurations >= 2.4',
  'Django-Crispy-Forms >= 2.0',
  'Django-Environ >= 0.9.0',
  'Django-Extensions >= 3.2.1',
  'Django-JSON-Widget >= 1.1.1',
  'Django-LocalFlavor >= 3.1',
  'Django-Nested-InLines >= 0.1',
  'Django-Storages >= 1.13.2',

  'Django-Query-Graph >= 0.0.0.dev1',
  'Dj-Util >= 0.0.0.dev1',

  # Django CORS Headers
  'Django-CORS-Headers >= 3.14.0',
    # let higher dependencies figure

  # Application UIs
  'Django-HTMX >= 1.14.0',

  # LATER: 'Django-Plotly-Dash >= 1.6.6',   # compatible with Django 4.1
  # LATER: 'Dash-Bootstrap-Components >= 0.13.1',   # compatible with Django-Plotly-Dash 1.6
  # LATER: 'DPD-Static-Support >= 0.0.5',
  # LATER: 'Django-Bootstrap4 >= 22.3',
  # LATER: 'WhiteNoise >= 6.3.0',

  'Gradio >= 3.19.1',
    # compatible with other dependencies

  'Streamlit >= 1.19.0',
  'Watchdog >= 2.3.0',

  # Database Adapters/Backends/Connectors/Drivers
  'MariaDB-DynCol >= 3.6.1',
  'Django-MySQL >= 4.9.0',
  'MySQLClient >= 2.1.1',
  'MySQL-Connector-Python >= 8.0.32',
  'PsycoPG2-binary >= 2.9.5',

  # ASGI Web Servers & related
  'ASGIRef >= 3.6.0',
  'Channels >= 4.0.0',
  'Daphne >= 4.0.0',
  'GUnicorn >= 20.1.0',
  # 'H11 >= 0.14.0',
    # let higher dependencies figure
  'Hypercorn >= 0.14.3',
  # 'Quart >= 0.18.3',
    # depends on Werkzeug >= 2.2.0
  'Starlette >= 0.25.0',
    # let higher dependencies figure
  'Uvicorn >= 0.20.0',


  # COMMAND-LINE INTERFACE (CLI)
  # ============================
  'CLICK >= 8.1.3',
    # let higher dependencies figure
  'Colored >= 1.4.4',


  # JUPYTER
  # =======
  # LATER: 'Jupyter >= 1.0.0',


  # MISC / OTHER
  # ============
  'GitPython >= 3.1.31',
  'Ruamel.YAML >= 0.17.21',
  'PSUtil >= 5.9.4',
  'Python-DateUtil >= 2.8.2',
  'Python-DotEnv >= 1.0.0',
  'PyTZ >= 2022.7.1',
  'Requests >= 2.28.2',
  'Tqdm >= 4.64.1',
  # LATER: 'Werkzeug >= 2.0, < 2.1',   # github.com/plotly/dash/issues/1992


  # CLOUD
  # =====

  # AWS deps: to install separately as they are notoriously hard to install alongside others
  # --------
  # 'AWSCLI ~= 1.21',
  # 'Boto3 ~= 1.19',

  # 'AWSEBCLI ~= 3.2',
    # too outdated
  # 'AWSWrangler >= 0.0.8',
    # too outdated
]


[project.optional-dependencies]
build = [
  'Build >= 0.10.0',
]

doc = [
  # Sphinx & related
  'Sphinx >= 6.1.3',
  'Sphinx-AutoBuild >= 2021.3.14',
  'SphinxContrib-JSMath >= 1.0.1',

  # Markdown
  'CommonMark >= 0.9.1',
  # 'MyST-Parser >= 0.18.1',  # depends on sphinx<6 and >=4
  'ReCommonMark >= 0.7.1',
]

lint = [
  'Bandit >= 1.7.4',
  'Flake8 >= 6.0.0',
  'MyPy >= 1.0.0',
  # 'Prospector >= 1.8.4',
  'PyCodeStyle >= 2.10.0',
  'PyDocStyle >= 6.3.0',
  'PyLama >= 8.4.1',
  'PyLint >= 2.16.1',
]

publish = [
  'Twine >= 4.0.2',
]

test = [
  'Nose >= 1.3.7',
  'Nose2 >= 0.12.0',
  'PyTest >= 7.2.1',
  'PyTest-Cov >= 4.0.0',
  'UnitTest2 >= 1.1.0',
]

viz = [
  'Altair >= 4.2.2',
  'Bokeh >= 3.0.3',
  'Dash >= 2.8.1',
  'Dash-DAQ >= 0.5.0',
  'PlotLy >= 5.13.0',
  'PlotNine >= 0.10.1',
  'Seaborn >= 0.12.2',
]


[project.scripts]
djaizz = 'djai.util.cli:djaizz'

# [project.gui-scripts]

# [project.entry-points."spam.magical"]


[project.urls]
Homepage = 'https://GitHub.com/Djaizz/Djaizz'
Repository = 'https://GitHub.com/Djaizz/Djaizz'
GitHub = 'https://GitHub.com/Djaizz/Djaizz'
Documentation = 'https://Djaizz.GitHub.io/Djaizz'


[build-system]
requires = [
  'SetUpTools >= 67.4.0',
  'Wheel >= 0.38.4',
]
build-backend = 'setuptools.build_meta'
