branch-defaults:
  default:
    environment: Djaizz
    group_suffix: null
  main:
    environment: Djaizz
    group_suffix: null
  master:
    environment: Djaizz
    group_suffix: null

global:
  application_name: Djaizz
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
