#!/usr/bin/env bash

# this scripts needs to be called from the Project's root dir


MODULE=src/djai
DOC_DIR=doc


# generate .rst files from module code & docstrings
# any pathnames given at the end are paths to be excluded ignored during generation.
# sphinx-doc.org/en/master/man/sphinx-apidoc.html
sphinx-apidoc \
    --force \
    --follow-links \
    --maxdepth 4 \
    --separate \
    --implicit-namespaces \
    --module-first \
    --output-dir $DOC_DIR $MODULE \
    *migrations*


# get rid of undocumented members
# grep -C2 ":undoc-members:" $DOC_DIR/$MODULE*.rst
sed -e /:undoc-members:/d -i .orig $DOC_DIR/$MODULE*.rst
rm $DOC_DIR/*.orig
